// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: proto/translation/translation.proto

package translation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for translation
type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`     // JWT authentication token
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // JSON string containing EEG data and mask
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_translation_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translation_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translation_translation_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TranslateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Response message for translation
type TranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translated    []string               `protobuf:"bytes,1,rep,name=translated,proto3" json:"translated,omitempty"`                         // Array of translated text outputs
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if translation fails
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_translation_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translation_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translation_translation_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetTranslated() []string {
	if x != nil {
		return x.Translated
	}
	return nil
}

func (x *TranslateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_translation_translation_proto protoreflect.FileDescriptor

const file_proto_translation_translation_proto_rawDesc = "" +
	"\n" +
	"#proto/translation/translation.proto\x12\vtranslation\"B\n" +
	"\x10TranslateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"X\n" +
	"\x11TranslateResponse\x12\x1e\n" +
	"\n" +
	"translated\x18\x01 \x03(\tR\n" +
	"translated\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2`\n" +
	"\x12TranslationService\x12J\n" +
	"\tTranslate\x12\x1d.translation.TranslateRequest\x1a\x1e.translation.TranslateResponseBKZIgithub.com/ThinkInkTeam/thinkink-core-backend/proto-gen/proto/translationb\x06proto3"

var (
	file_proto_translation_translation_proto_rawDescOnce sync.Once
	file_proto_translation_translation_proto_rawDescData []byte
)

func file_proto_translation_translation_proto_rawDescGZIP() []byte {
	file_proto_translation_translation_proto_rawDescOnce.Do(func() {
		file_proto_translation_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_translation_translation_proto_rawDesc), len(file_proto_translation_translation_proto_rawDesc)))
	})
	return file_proto_translation_translation_proto_rawDescData
}

var file_proto_translation_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_translation_translation_proto_goTypes = []any{
	(*TranslateRequest)(nil),  // 0: translation.TranslateRequest
	(*TranslateResponse)(nil), // 1: translation.TranslateResponse
}
var file_proto_translation_translation_proto_depIdxs = []int32{
	0, // 0: translation.TranslationService.Translate:input_type -> translation.TranslateRequest
	1, // 1: translation.TranslationService.Translate:output_type -> translation.TranslateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_translation_translation_proto_init() }
func file_proto_translation_translation_proto_init() {
	if File_proto_translation_translation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_translation_translation_proto_rawDesc), len(file_proto_translation_translation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translation_translation_proto_goTypes,
		DependencyIndexes: file_proto_translation_translation_proto_depIdxs,
		MessageInfos:      file_proto_translation_translation_proto_msgTypes,
	}.Build()
	File_proto_translation_translation_proto = out.File
	file_proto_translation_translation_proto_goTypes = nil
	file_proto_translation_translation_proto_depIdxs = nil
}
