// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: proto/validation/validation.proto

package validation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for token validation
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token to validate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_validation_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_validation_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateTokenResponse returns validation result
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_validation_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validation_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_validation_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_proto_validation_validation_proto protoreflect.FileDescriptor

const file_proto_validation_validation_proto_rawDesc = "" +
	"\n" +
	"!proto/validation/validation.proto\x12\n" +
	"validation\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x15ValidateTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2p\n" +
	"\x16TokenValidationService\x12V\n" +
	"\x0fValidateMLToken\x12 .validation.ValidateTokenRequest\x1a!.validation.ValidateTokenResponseBJZHgithub.com/ThinkInkTeam/thinkink-core-backend/proto-gen/proto/validationb\x06proto3"

var (
	file_proto_validation_validation_proto_rawDescOnce sync.Once
	file_proto_validation_validation_proto_rawDescData []byte
)

func file_proto_validation_validation_proto_rawDescGZIP() []byte {
	file_proto_validation_validation_proto_rawDescOnce.Do(func() {
		file_proto_validation_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_validation_validation_proto_rawDesc), len(file_proto_validation_validation_proto_rawDesc)))
	})
	return file_proto_validation_validation_proto_rawDescData
}

var file_proto_validation_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_validation_validation_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: validation.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 1: validation.ValidateTokenResponse
}
var file_proto_validation_validation_proto_depIdxs = []int32{
	0, // 0: validation.TokenValidationService.ValidateMLToken:input_type -> validation.ValidateTokenRequest
	1, // 1: validation.TokenValidationService.ValidateMLToken:output_type -> validation.ValidateTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_validation_validation_proto_init() }
func file_proto_validation_validation_proto_init() {
	if File_proto_validation_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_validation_validation_proto_rawDesc), len(file_proto_validation_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_validation_validation_proto_goTypes,
		DependencyIndexes: file_proto_validation_validation_proto_depIdxs,
		MessageInfos:      file_proto_validation_validation_proto_msgTypes,
	}.Build()
	File_proto_validation_validation_proto = out.File
	file_proto_validation_validation_proto_goTypes = nil
	file_proto_validation_validation_proto_depIdxs = nil
}
